### ISSUE TITLE
mpd_demo.rb

### ISSUE THREAD

**Issue by lubino** [kfigiela/denon-raspberry#1]
I am trying to run 
`ruby mpd_demo.rb`

It ends with this result
/var/lib/gems/2.1.0/gems/ruby-mpd-0.3.1/lib/ruby-mpd.rb:144:in 'initialize': Connection refused - connect(2) for "localhost" port 6600 (Errno::ECONNREFUSED)
    from /var/lib/gems/2.1.0/gems/ruby-mpd-0.3.1/lib/ruby-mpd.rb:144:in 'new'
    from /var/lib/gems/2.1.0/gems/ruby-mpd-0.3.1/lib/ruby-mpd.rb:144:in 'connect'
    from mpd_demo.rb:142:in 'block in < main >'
    from /var/lib/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in 'call'
    from /var/lib/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in 'run_machine'
    from /var/lib/gems/2.1.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in 'run'
    from mpd_demo.rb:140:in '< main >'

What is wrong with my configuration?
Thanks a lot.

**Comment by lubino** [comment]
Also `ruby web_ui.rb`

web_ui.rb:18:in 'class:WebSocketUI': uninitialized constant WebSocketUI::MPDOperations (NameError)
    from web_ui.rb:17:in '< main >'
